import { Themes, type StyleVars } from '@varlet/ui'

// 霓虹渐变 (紫 → 蓝 → 粉), 供自定义样式使用 (背景光晕/标题渐变/按钮等)。
// 自定义变量会随 StyleProvider 一并注入为 CSS 变量。

export const lightTheme: StyleVars = {
  ...Themes.md3Light,
  // ---- 自定义: 霓虹渐变 & 玻璃面板 & 圆角 ----
  '--gradient-primary': 'linear-gradient(135deg, #7C3AED 0%, #3B82F6 50%, #EC4899 100%)',
  '--gradient-soft': 'linear-gradient(135deg, rgba(124,58,237,0.12), rgba(59,130,246,0.12), rgba(236,72,153,0.12))',
  '--glass-bg': 'rgba(255, 255, 255, 0.72)',
  '--glass-border': 'rgba(255, 255, 255, 0.6)',
  '--glass-blur': '16px',
  '--card-radius': '14px',
  '--card-shadow': '0 4px 20px rgba(124, 58, 237, 0.08), 0 2px 8px rgba(0, 0, 0, 0.06)',
  '--card-shadow-hover': '0 12px 32px rgba(124, 58, 237, 0.18), 0 4px 12px rgba(0, 0, 0, 0.1)',

  // ---- Varlet 主色: 紫 ----
  '--hsl-primary': '262, 83%, 58%',
  '--color-primary': 'hsla(var(--hsl-primary), 1)',
  '--hsl-on-primary': '0, 0%, 100%',
  '--color-on-primary': 'hsla(var(--hsl-on-primary), 1)',
  '--hsl-primary-container': '262, 100%, 92%',
  '--color-primary-container': 'hsla(var(--hsl-primary-container), 1)',
  '--hsl-on-primary-container': '262, 80%, 24%',
  '--color-on-primary-container': 'hsla(var(--hsl-on-primary-container), 1)',

  // ---- 辅助色: 蓝(info) / 琥珀(warning) / 粉(danger) ----
  '--hsl-info': '217, 91%, 50%',
  '--color-info': 'hsla(var(--hsl-info), 1)',
  '--hsl-on-info': '0, 0%, 100%',
  '--color-on-info': 'hsla(var(--hsl-on-info), 1)',
  '--hsl-info-container': '213, 100%, 90%',
  '--color-info-container': 'hsla(var(--hsl-info-container), 1)',
  '--hsl-on-info-container': '217, 90%, 20%',
  '--color-on-info-container': 'hsla(var(--hsl-on-info-container), 1)',
  '--hsl-warning': '38, 92%, 50%',
  '--color-warning': 'hsla(var(--hsl-warning), 1)',
  '--hsl-on-warning': '0, 0%, 100%',
  '--color-on-warning': 'hsla(var(--hsl-on-warning), 1)',
  '--hsl-warning-container': '40, 100%, 90%',
  '--color-warning-container': 'hsla(var(--hsl-warning-container), 1)',
  '--hsl-on-warning-container': '35, 90%, 20%',
  '--color-on-warning-container': 'hsla(var(--hsl-on-warning-container), 1)',
  '--hsl-danger': '330, 81%, 55%',
  '--color-danger': 'hsla(var(--hsl-danger), 1)',
  '--hsl-on-danger': '0, 0%, 100%',
  '--color-on-danger': 'hsla(var(--hsl-on-danger), 1)',
  '--hsl-danger-container': '330, 100%, 92%',
  '--color-danger-container': 'hsla(var(--hsl-danger-container), 1)',
  '--hsl-on-danger-container': '330, 90%, 22%',
  '--color-on-danger-container': 'hsla(var(--hsl-on-danger-container), 1)',

  // ---- 表面 & 文字 ----
  '--hsl-body': '240, 20%, 97%',
  '--color-body': 'hsla(var(--hsl-body), 1)',
  '--hsl-surface-container': '0, 0%, 100%',
  '--color-surface-container': 'hsla(var(--hsl-surface-container), 1)',
  '--hsl-surface-container-low': '240, 20%, 98%',
  '--color-surface-container-low': 'hsla(var(--hsl-surface-container-low), 1)',
  '--hsl-surface-container-high': '240, 20%, 95%',
  '--color-surface-container-high': 'hsla(var(--hsl-surface-container-high), 1)',
  '--hsl-text': '240, 10%, 12%',
  '--color-text': 'hsla(var(--hsl-text), 1)',
  '--hsl-on-surface-variant': '240, 6%, 35%',
  '--color-on-surface-variant': 'hsla(var(--hsl-on-surface-variant), 1)',
  '--hsl-outline': '240, 6%, 55%',
  '--color-outline': 'hsla(var(--hsl-outline), 1)',
  '--hsl-inverse-surface': '240, 10%, 15%',
  '--color-inverse-surface': 'hsla(var(--hsl-inverse-surface), 1)'
}

export const darkTheme: StyleVars = {
  ...Themes.md3Dark,
  // ---- 自定义: 霓虹渐变 & 玻璃面板 & 圆角 (暗色下渐变更亮) ----
  '--gradient-primary': 'linear-gradient(135deg, #A78BFA 0%, #60A5FA 50%, #F472B6 100%)',
  '--gradient-soft': 'linear-gradient(135deg, rgba(167,139,250,0.10), rgba(96,165,250,0.10), rgba(244,114,182,0.10))',
  '--glass-bg': 'rgba(22, 22, 30, 0.7)',
  '--glass-border': 'rgba(255, 255, 255, 0.08)',
  '--glass-blur': '16px',
  '--card-radius': '14px',
  '--card-shadow': '0 4px 20px rgba(0, 0, 0, 0.4)',
  '--card-shadow-hover': '0 12px 36px rgba(124, 58, 237, 0.25), 0 4px 12px rgba(0, 0, 0, 0.5)',

  // ---- Varlet 主色: 亮紫 (暗色下用高亮紫, 接近 MD3 规范) ----
  '--hsl-primary': '258, 100%, 82%',
  '--color-primary': 'hsla(var(--hsl-primary), 1)',
  '--hsl-on-primary': '258, 80%, 22%',
  '--color-on-primary': 'hsla(var(--hsl-on-primary), 1)',
  '--hsl-primary-container': '260, 45%, 28%',
  '--color-primary-container': 'hsla(var(--hsl-primary-container), 1)',
  '--hsl-on-primary-container': '258, 100%, 90%',
  '--color-on-primary-container': 'hsla(var(--hsl-on-primary-container), 1)',

  // ---- 辅助色 ----
  '--hsl-info': '217, 90%, 72%',
  '--color-info': 'hsla(var(--hsl-info), 1)',
  '--hsl-on-info': '217, 90%, 18%',
  '--color-on-info': 'hsla(var(--hsl-on-info), 1)',
  '--hsl-info-container': '217, 40%, 24%',
  '--color-info-container': 'hsla(var(--hsl-info-container), 1)',
  '--hsl-on-info-container': '213, 100%, 88%',
  '--color-on-info-container': 'hsla(var(--hsl-on-info-container), 1)',
  '--hsl-warning': '38, 92%, 68%',
  '--color-warning': 'hsla(var(--hsl-warning), 1)',
  '--hsl-on-warning': '38, 90%, 18%',
  '--color-on-warning': 'hsla(var(--hsl-on-warning), 1)',
  '--hsl-warning-container': '38, 40%, 26%',
  '--color-warning-container': 'hsla(var(--hsl-warning-container), 1)',
  '--hsl-on-warning-container': '40, 100%, 88%',
  '--color-on-warning-container': 'hsla(var(--hsl-on-warning-container), 1)',
  '--hsl-danger': '330, 100%, 76%',
  '--color-danger': 'hsla(var(--hsl-danger), 1)',
  '--hsl-on-danger': '330, 90%, 20%',
  '--color-on-danger': 'hsla(var(--hsl-on-danger), 1)',
  '--hsl-danger-container': '330, 45%, 26%',
  '--color-danger-container': 'hsla(var(--hsl-danger-container), 1)',
  '--hsl-on-danger-container': '330, 100%, 88%',
  '--color-on-danger-container': 'hsla(var(--hsl-on-danger-container), 1)',

  // ---- 表面 & 文字: 深空黑 + 深灰卡片 ----
  '--hsl-body': '240, 20%, 5%',
  '--color-body': 'hsla(var(--hsl-body), 1)',
  '--hsl-surface-container': '240, 13%, 10%',
  '--color-surface-container': 'hsla(var(--hsl-surface-container), 1)',
  '--hsl-surface-container-low': '240, 14%, 7%',
  '--color-surface-container-low': 'hsla(var(--hsl-surface-container-low), 1)',
  '--hsl-surface-container-high': '240, 12%, 13%',
  '--color-surface-container-high': 'hsla(var(--hsl-surface-container-high), 1)',
  '--hsl-surface-container-highest': '240, 10%, 17%',
  '--color-surface-container-highest': 'hsla(var(--hsl-surface-container-highest), 1)',
  '--hsl-text': '240, 10%, 92%',
  '--color-text': 'hsla(var(--hsl-text), 1)',
  '--hsl-on-surface-variant': '240, 8%, 70%',
  '--color-on-surface-variant': 'hsla(var(--hsl-on-surface-variant), 1)',
  '--hsl-outline': '240, 6%, 45%',
  '--color-outline': 'hsla(var(--hsl-outline), 1)',
  '--hsl-inverse-surface': '240, 10%, 90%',
  '--color-inverse-surface': 'hsla(var(--hsl-inverse-surface), 1)'
}
