import { Themes, type StyleVars } from '@varlet/ui'

export const lightTheme: StyleVars = {
  ...Themes.md3Light,
  '--hsl-primary': '187, 100%, 23%',
  '--color-primary': 'hsla(var(--hsl-primary), 1)',
  '--hsl-on-primary': '0, 0%, 100%',
  '--color-on-primary': 'hsla(var(--hsl-on-primary), 1)',
  '--hsl-primary-container': '190, 100%, 81%',
  '--color-primary-container': 'hsla(var(--hsl-primary-container), 1)',
  '--hsl-on-primary-container': '188, 100%, 7%',
  '--color-on-primary-container': 'hsla(var(--hsl-on-primary-container), 1)',
  '--hsl-info': '190, 16%, 35%',
  '--color-info': 'hsla(var(--hsl-info), 1)',
  '--hsl-on-info': '0, 0%, 100%',
  '--color-on-info': 'hsla(var(--hsl-on-info), 1)',
  '--hsl-info-container': '191, 47%, 87%',
  '--color-info-container': 'hsla(var(--hsl-info-container), 1)',
  '--hsl-on-info-container': '188, 75%, 8%',
  '--color-on-info-container': 'hsla(var(--hsl-on-info-container), 1)',
  '--hsl-warning': '226, 21%, 41%',
  '--color-warning': 'hsla(var(--hsl-warning), 1)',
  '--hsl-on-warning': '0, 0%, 100%',
  '--color-on-warning': 'hsla(var(--hsl-on-warning), 1)',
  '--hsl-warning-container': '230, 100%, 93%',
  '--color-warning-container': 'hsla(var(--hsl-warning-container), 1)',
  '--hsl-on-warning-container': '225, 55%, 14%',
  '--color-on-warning-container': 'hsla(var(--hsl-on-warning-container), 1)',
  '--hsl-danger': '0, 75%, 42%',
  '--color-danger': 'hsla(var(--hsl-danger), 1)',
  '--hsl-on-danger': '0, 0%, 100%',
  '--color-on-danger': 'hsla(var(--hsl-on-danger), 1)',
  '--hsl-danger-container': '6, 100%, 92%',
  '--color-danger-container': 'hsla(var(--hsl-danger-container), 1)',
  '--hsl-on-danger-container': '358, 100%, 13%',
  '--color-on-danger-container': 'hsla(var(--hsl-on-danger-container), 1)',
  '--hsl-body': '210, 33%, 96%',
  '--color-body': 'hsla(var(--hsl-body), 1)',
  '--hsl-text': '195, 7%, 11%',
  '--color-text': 'hsla(var(--hsl-text), 1)',
  '--hsl-on-surface-variant': '191, 8%, 27%',
  '--color-on-surface-variant': 'hsla(var(--hsl-on-surface-variant), 1)',
  '--hsl-outline': '190, 5%, 46%',
  '--color-outline': 'hsla(var(--hsl-outline), 1)',
  '--hsl-inverse-surface': '195, 4%, 19%',
  '--color-inverse-surface': 'hsla(var(--hsl-inverse-surface), 1)'
}

export const darkTheme: StyleVars = {
  ...Themes.md3Dark,
  '--hsl-primary': '188, 88%, 56%',
  '--color-primary': 'hsla(var(--hsl-primary), 1)',
  '--hsl-on-primary': '188, 100%, 12%',
  '--color-on-primary': 'hsla(var(--hsl-on-primary), 1)',
  '--hsl-primary-container': '187, 100%, 17%',
  '--color-primary-container': 'hsla(var(--hsl-primary-container), 1)',
  '--hsl-on-primary-container': '190, 100%, 81%',
  '--color-on-primary-container': 'hsla(var(--hsl-on-primary-container), 1)',
  '--hsl-info': '191, 26%, 76%',
  '--color-info': 'hsla(var(--hsl-info), 1)',
  '--hsl-on-info': '190, 34%, 17%',
  '--color-on-info': 'hsla(var(--hsl-on-info), 1)',
  '--hsl-info-container': '189, 22%, 25%',
  '--color-info-container': 'hsla(var(--hsl-info-container), 1)',
  '--hsl-on-info-container': '191, 47%, 87%',
  '--color-on-info-container': 'hsla(var(--hsl-on-info-container), 1)',
  '--hsl-warning': '228, 55%, 83%',
  '--color-warning': 'hsla(var(--hsl-warning), 1)',
  '--hsl-on-warning': '225, 35%, 22%',
  '--color-on-warning': 'hsla(var(--hsl-on-warning), 1)',
  '--hsl-warning-container': '225, 25%, 32%',
  '--color-warning-container': 'hsla(var(--hsl-warning-container), 1)',
  '--hsl-on-warning-container': '230, 100%, 93%',
  '--color-on-warning-container': 'hsla(var(--hsl-on-warning-container), 1)',
  '--hsl-danger': '6, 100%, 84%',
  '--color-danger': 'hsla(var(--hsl-danger), 1)',
  '--hsl-on-danger': '357, 100%, 21%',
  '--color-on-danger': 'hsla(var(--hsl-on-danger), 1)',
  '--hsl-danger-container': '356, 100%, 29%',
  '--color-danger-container': 'hsla(var(--hsl-danger-container), 1)',
  '--hsl-on-danger-container': '6, 100%, 84%',
  '--color-on-danger-container': 'hsla(var(--hsl-on-danger-container), 1)',
  '--hsl-body': '195, 7%, 11%',
  '--color-body': 'hsla(var(--hsl-body), 1)',
  '--hsl-text': '180, 3%, 89%',
  '--color-text': 'hsla(var(--hsl-text), 1)',
  '--hsl-on-surface-variant': '191, 9%, 77%',
  '--color-on-surface-variant': 'hsla(var(--hsl-on-surface-variant), 1)',
  '--hsl-outline': '191, 5%, 56%',
  '--color-outline': 'hsla(var(--hsl-outline), 1)',
  '--hsl-inverse-surface': '180, 3%, 89%',
  '--color-inverse-surface': 'hsla(var(--hsl-inverse-surface), 1)'
}
